version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.13
    commands:
      - pip install -r lambda_layer/requirements.txt -t python/
  build:
    commands:
      - cp lambda_layer/*.py python/
      - zip -r layer.zip python/
      - aws lambda publish-layer-version \
        --layer-name dary-application-lambda-layer \
        --zip-file fileb://layer.zip \
        --compatible-runtimes python3.13 \
        --region us-east-1
artifacts:
  files:
    - layer.zip
