name: Deploy Lambda Layer

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Build and Deploy Lambda Layer
    runs-on: ubuntu-latest

    env:
      LAYER_NAME: dary-application-lambda-layer
      PYTHON_VERSION: 3.13

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          mkdir -p layer/python
          pip install -r lambda_layer/requirements.txt -t layer/python
          cp lambda_layer/*.py layer/python/

      - name: Zip layer content
        run: |
          cd layer
          zip -r ../layer.zip python
          cd ..

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Publish new Lambda Layer version
        run: |
          aws lambda publish-layer-version \
            --layer-name $LAYER_NAME \
            --zip-file fileb://layer.zip \
            --compatible-runtimes python${{ env.PYTHON_VERSION }} \
            --region ${{ secrets.AWS_REGION }}
